[colors.primary]
background = "#f8f9fa"  # Slightly lighter than Nord6 for better contrast
foreground = "#242933"  # Slightly darker than Nord0 for better readability

[colors.normal]
black = "#1e222a"       # Darker than Nord0 for better contrast
red = "#a54242"         # Darker red for better readability
green = "#8f9a6b"       # Darker green for better contrast
yellow = "#c49619"      # Much darker yellow/orange for git warnings
blue = "#4a6b8a"        # Darker blue for better contrast
magenta = "#9c6ba6"     # Darker purple for better readability
cyan = "#6ba3b8"        # Darker cyan for better contrast
white = "#2e3440"       # Nord0 unchanged

[colors.bright]
black = "#2e3440"       # Nord0 for bright black
red = "#bf616a"         # Original Aurora Red for bright
green = "#a3be8c"       # Original Aurora Green for bright
yellow = "#d4930f"      # Slightly darker bright yellow for contrast
blue = "#5e81ac"        # Original Frost Blue
magenta = "#b48ead"     # Original Aurora Purple
cyan = "#7fb4ca"        # Slightly darker bright cyan
white = "#1a1e26"       # Very dark for bright white

[colors.dim]
black = "#3b4252"       # Nord1 for dim black
red = "#8a4a4a"         # Much darker red for dim
green = "#6b7a52"       # Much darker green for dim
yellow = "#a67c14"      # Much darker yellow for git warnings
blue = "#3d5573"        # Much darker blue for dim
magenta = "#7a5a7a"     # Much darker purple for dim
cyan = "#52849c"        # Much darker cyan for dim
white = "#434c5e"       # Nord2 for dim white

# Selection colors
[colors.selection]
text = "#1e222a"        # Very dark text for selection
background = "#d0d7e0"  # Darker selection background for contrast

# Search colors
[colors.search.matches]
foreground = "#1e222a"  # Very dark text for search
background = "#c49619"  # Darker yellow for better contrast

[colors.search.focused_match]
foreground = "#f8f9fa"  # Light text on dark background
background = "#b8540a"  # Much darker orange for focused search
