[colors.primary]
background = "#2e3440"  # Nord0 - Polar Night
foreground = "#d8dee9"  # Nord4 - Snow Storm

[colors.normal]
black = "#3b4252"       # Nord1 - Polar Night
red = "#bf616a"         # Nord11 - Aurora Red
green = "#a3be8c"       # Nord14 - Aurora Green
yellow = "#ebcb8b"      # Nord13 - Aurora Yellow
blue = "#81a1c1"        # Nord10 - Frost Blue
magenta = "#b48ead"     # Nord15 - Aurora Purple
cyan = "#88c0d0"        # Nord8 - Frost Cyan
white = "#e5e9f0"       # Nord5 - Snow Storm

[colors.bright]
black = "#4c566a"       # Nord3 - Polar Night
red = "#bf616a"         # Nord11 - Aurora Red
green = "#a3be8c"       # Nord14 - Aurora Green
yellow = "#ebcb8b"      # Nord13 - Aurora Yellow
blue = "#81a1c1"        # Nord10 - Frost Blue
magenta = "#b48ead"     # Nord15 - Aurora Purple
cyan = "#8fbcbb"        # Nord7 - Frost Teal
white = "#eceff4"       # Nord6 - Snow Storm

[colors.dim]
black = "#373e4d"       # Dimmed Nord1
red = "#94545d"         # Dimmed Aurora Red
green = "#809575"       # Dimmed Aurora Green
yellow = "#b29e75"      # Dimmed Aurora Yellow
blue = "#68809a"        # Dimmed Frost Blue
magenta = "#8c738c"     # Dimmed Aurora Purple
cyan = "#6d96a5"        # Dimmed Frost Cyan
white = "#aeb3bb"       # Dimmed Snow Storm

# Selection colors
[colors.selection]
text = "#2e3440"        # Nord0
background = "#434c5e"  # Nord2

# Search colors
[colors.search.matches]
foreground = "#2e3440"  # Nord0
background = "#ebcb8b"  # Nord13 - Aurora Yellow

[colors.search.focused_match]
foreground = "#2e3440"  # Nord0
background = "#d08770"  # Nord12 - Aurora Orange
